config/routes.rb
Gtd::Application.routes.draw do
  resources :contexts

end

app/models/context.rb
class Context < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  # GET /contexts
  # GET /contexts.json
  def index
    @contexts = Context.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: ContextsDatatable.new(view_context)}
    end
  end

  # GET /contexts/1
  # GET /contexts/1.json
  def show
    @context = Context.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @context }
    end
  end

  # GET /contexts/new
  # GET /contexts/new.json
  def new
    @context = Context.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @context }
    end
  end

  # GET /contexts/1/edit
  def edit
    @context = Context.find(params[:id])
  end

  # POST /contexts
  # POST /contexts.json
  def create
    @context = Context.new(params[:context])

    respond_to do |format|
      if @context.save
        format.html { redirect_to @context, notice: 'Context was successfully created.' }
        format.json { render json: @context, status: :created, location: @context }
      else
        format.html { render action: "new" }
        format.json { render json: @context.errors, status: :unprocessable_entity }
      end
    end
  end

  #x PUT /contexts/1
  # PUT /contexts/1.json
  def update
    @context = Context.find(params[:id])

    respond_to do |format|
      if @context.update_attributes(params[:context])
        format.html { redirect_to @context, notice: 'Context was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @context.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contexts/1
  # DELETE /contexts/1.json
  def destroy
    @context = Context.find(params[:id])
    @context.destroy

    respond_to do |format|
      format.html { redirect_to contexts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def full_title(page_title)
  base_title = "Ruby on Rails Tutorial Sample App"
  if page_title.empty?
    base_title
  else
    "#{base_title} | #{page_title}"
  end
end

end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/views/contexts/_form.html.erb
<%= form_for(@context) do |f| %>
  <% if @context.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@context.errors.count, "error") %> prohibited this context from being saved:</h2>

      <ul>
      <% @context.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contexts/edit.html.erb
<h1>Editing context</h1>

<%= render 'form' %>

<%= link_to 'Show', @context %> |
<%= link_to 'Back', contexts_path %>

app/views/contexts/index.html.erb
<% provide(:title, 'Home') %>
<div style="width:800px">
<div  class="ui-tabs-nav ui-widget-header ui-corner-all " style="float:left; width:100%">
  <div style="margin:2px;">
    <div style="float:left; font-weight:300; font-size: 18px; padding: 3px; padding-right:20px;" class="ui-state-default ui-corner-all">Contexts</div>
       <ul class="ui-widget ui-helper-clearfix ui-corner-all" style="margin: 2px; padding: 4px 0;cursor: pointer;float:right; list-style: none;">
          <li id="addIcon" class="ui-state-default ui-corner-all" title="Add Context">
            <span class="ui-icon ui-icon-circle-plus"></span>
          </li>
      </ul>
  </div>
</div>
  <div style="clear: both;"></div>
<div class="full_width" style="margin-top:1em; ">
  <table id="products" class="display" data-source="<%= contexts_url(format: "json")%>">
    <thead>
      <tr class="Grade A">
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>
</div>

app/views/contexts/new.html.erb
<h1>New context</h1>

<%= render 'form' %>

<%= link_to 'Back', contexts_path %>

app/views/contexts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @context.name %>
</p>

<p>
  <b>Description:</b>
  <%= @context.description %>
</p>


<%= link_to 'Edit', edit_context_path(@context) %> |
<%= link_to 'Back', contexts_path %>

app/views/layouts/_footer.html.erb
  <footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    '#' %></li>
          <li><%= link_to "Help",    '#' %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>